# FILETYPES
CURRENTLY_SUPPORTED_FILETYPES = ['Shapefile', 'CSV', 'JSON', 'DB', 'netCDF', 'CSVW', 'XML']
GEOSPATIAL_FILETYPES = ['Shapefile', 'GML', 'KML', 'GeoJson']
OTHER_FILETYPES = ['CSV', 'JSON', 'XML', 'DB', 'netCDF', 'CSVW']

# UTILS
DEFAULT_CRS = 4326

# YARRRML
YARRML_INPUT_DATA_FIELDNAME = 'sources'
YARRML_SUPPORTED_DATA_TYPES = ['CSV', 'XML', 'JSON']

# GENERAL MAPPING GENERATOR
GENERATED_MAPPING_FILENAME = "generated_mapping.ttl"
