import logging
import os
import datetime
import subprocess
import sys

import yaml
from ruamel.yaml import YAML

from modules.tools import basic_tool
from modules.utils.utils import is_path_abs, get_paths_normalized_basename
from modules.settings import YARRML_INPUT_DATA_FIELDNAME


class YARRRML(basic_tool.Tool):
    """
    Class that uses Yarrrml tool to generate mappings.
    """

    def __init__(self, results_dir):
        super().__init__()
        self.directory = None
        self.executable = 'yarrrml-parser'
        self.results_dir = results_dir

        # setting up logger
        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.DEBUG)
        self.formatter = logging.Formatter('%(asctime)s:%(levelname)s:%(message)s')
        current_date = datetime.datetime.now()
        self.log_path = os.path.join('logs',
                                     f'pipeline_yarrrml_'
                                     f'{current_date.year}-{current_date.month}-{current_date.day}.log')
        self.file_handler = logging.FileHandler(self.log_path)
        self.file_handler.setFormatter(self.formatter)
        self.logger.addHandler(self.file_handler)

    def run_yarrrml(self, rules_file, input_data_files, mapping_dir):
        """
        Function that runs csv2rdf to generate mappings.
        :param rules_file: str -> yaml file that provides rules for mapping generation
        :param input_data_files: list -> list of input source files, only data types that are supported by yarrrml tool
        :param mapping_dir: str -> output dir for storing mapping that will be generated by yarrrml parser.
        """
        cwd = os.getcwd()
        self.logger.info(f"{rules_file=}")
        if is_path_abs(rules_file):
            input_rules_full_path = rules_file
        else:
            input_rules_full_path = os.path.join(cwd, rules_file)
        self.logger.info(f"{input_rules_full_path=}")
        input_filename = os.path.splitext(get_paths_normalized_basename(input_rules_full_path))[0]
        self.logger.info(f"{input_filename=}")
        updated_rules_full_path = self._modify_path_inside_rules_file(rules_file=input_rules_full_path,
                                                                      input_files=input_data_files,
                                                                      rules_filename=input_filename)
        output_full_path = os.path.join(cwd, mapping_dir, f"{input_filename}.ttl")
        self.logger.info(f"{output_full_path=}")
        with open(self.log_path, 'wb') as log:
            p = subprocess.Popen([self.executable, '-i', updated_rules_full_path, '-o', output_full_path], shell=False,
                                 stderr=log)
        p.communicate()

    @staticmethod
    def _adjust_paths(dct, input_files):
        """
        Semi-private helper function for adjusting all paths in the rules file.
        """
        def iterate(dct):
            for k, v in dct.items():
                if isinstance(v, dict):
                    if "access" not in v.keys():
                        iterate(dct=v)
                    else:
                        to_be_updated = v.get("access")
                        for file in input_files:
                            if get_paths_normalized_basename(file) == get_paths_normalized_basename(to_be_updated):
                                v["access"] = file

                elif isinstance(v, list):
                    for item in v:
                        if isinstance(item, dict):
                            if "access" in item.keys():
                                to_be_updated = item.get("access")
                                for file in input_files:
                                    if get_paths_normalized_basename(file) == get_paths_normalized_basename(
                                            to_be_updated):
                                        item["access"] = file
                        if isinstance(item, list):
                            to_be_updated = item[0].split("~")[0]
                            reference_formulation = item[0].split("~")[-1]
                            for file in input_files:
                                if get_paths_normalized_basename(file) == get_paths_normalized_basename(to_be_updated):
                                    item[0] = file + "~" + reference_formulation

        iterate(dct)
        return dct

    def _modify_path_inside_rules_file(self, rules_file, input_files, rules_filename):
        """
        Semi-private helper function for adjusting data path inside yaml file that provides rules for yarrrml tool.
        :param input_files: list of source data file. Can be any type that is supported by the yarrrml tool
        :param rules_file: yaml file that provides rules for mapping generation
        :param rules_filename: str, rules filename
        """
        yml = YAML()
        yml.width = sys.maxsize
        with open(rules_file, 'r') as f:
            cfg = yml.load(f)

            outside_portion = None
            for k, v in cfg.items():
                if k == YARRML_INPUT_DATA_FIELDNAME:
                    outside_portion = v
                else:
                    self._adjust_paths(dct=v, input_files=input_files)
            if outside_portion:
                self._adjust_paths(dct=outside_portion, input_files=input_files)

        updated_rules_output_path = os.path.join(self.results_dir, rules_filename + '.yml')
        self.logger.info(f"{updated_rules_output_path=}")
        with open(updated_rules_output_path, 'w') as opt:
            yml.default_flow_style = True
            yml.dump(cfg, opt)
        return updated_rules_output_path

